Feat/shipment view
BrianBts/box-client pull request #33
Opened 2023-11-14 23:42 UTC by agtorroja

2023-11-14 23:42 UTC, darioberatti approved these changes

2023-11-15 00:56 UTC, BrianBts requested changes

2023-11-15 00:56 UTC, BrianBts commented on src/components/ShipmentView.tsx
> +import CarrierCard from "components/CarrierCard";
Exportar desde index.ts para importarlo de la siguiente manera

Import { CarrierCard } from "components"

2023-11-15 00:56 UTC, BrianBts commented on src/components/ShipmentView.tsx
> +export default function ShipmentView() {
Borrar default

2023-11-15 13:10 UTC, MateoNava approved these changes

2023-11-15 14:47 UTC, BrianBts approved these changes

2023-11-15 14:47 UTC, merged